[xfuse]
network_depth = 6
network_width = 16
gene_regex = "^(?!RPS|RPL|MT-).*" # remove ribo and mito genes
min_counts = 1

[settings]
cache_data = true
data_workers = 8

[expansion_strategy]
type = "DropAndSplit"
[expansion_strategy.DropAndSplit]
max_metagenes = 50

[optimization]
batch_size = 3
epochs = 30000
learning_rate = 0.0003
patch_size = 768

[analyses]
[analyses.analysis-gene_maps]
type = "gene_maps"
[analyses.analysis-gene_maps.options]
gene_regex = ".*"
num_samples = 10
genes_per_batch = 10
predict_mean = true
normalize = false
mask_tissue = true
scale = 1.0
writer = "image"
[analyses.analysis-metagenes]
type = "metagenes"
[analyses.analysis-metagenes.options]
method = "pca"

[slides]
[slides.section1]
data = "visium_heart_lv_processed_sct/data.h5"
